[package]
name = "catty"
version = "0.1.0"
edition = "2021"

[features]
dev_mode = []

[dependencies]
audiotags = "0.5.0"
toml = "0.8.20"
which = "7.0.2"
log = "0.4.25"
colog = "1.3.0"
clap = { version = "4.5.29", features = ["derive"] }